version: '3.8'

services:
  web:
    build: .  # Build from local Dockerfile instead of using remote image
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data  # Mount a data directory for persistent storage
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - RELOAD=false
      - DATABASE_DIR=/app/data
    restart: unless-stopped 